[workspace]
members = [
  "yew-struct-components/counter",
  "yew-struct-components/fetch",
  "yew-struct-components/helloworld",
  "yew-struct-components/iterator",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1

