[package]
name = "yew-counter"
version = "0.1.0"
authors = [ "Hanabusa Masahiro" ]
edition = "2021"
workspace = "../../"

[dependencies]
wasm-bindgen = "=0.2.83"
yew = { version = "0.20", features = ["csr"] }

